package cluster

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeUserConfig(t *testing.T, content string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "ceph.conf")
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}

func TestWithConfigFileParsesNativeSyntax(t *testing.T) {
	path := writeUserConfig(t, strings.Join([]string{
		"# tuning for small fixtures",
		"[ global ]",
		"mgr stats period = 2 ; faster than the default",
		"",
		"[osd]\r",
		"osd-memory-target = 1073741824",
		"Osd_Op_Num_Shards = 1",
		"[client.admin]",
		`rgw_enable_usage_log = "true"`,
		`debug_rgw = 1\#literal`,
		"[mds]",
		"; empty sections are dropped",
		"[global]",
		"osd_pool_default_pg_num = 4",
	}, "\n"))
	var o options
	if err := WithConfigFile(path)(&o); err != nil {
		t.Fatal(err)
	}
	want := strings.Join([]string{
		"[global]",
		"mgr_stats_period = 2",
		"osd_pool_default_pg_num = 4",
		"[osd]",
		"osd_memory_target = 1073741824",
		"Osd_Op_Num_Shards = 1",
		"[client.admin]",
		`rgw_enable_usage_log = "true"`,
		`debug_rgw = 1\#literal`,
		"",
	}, "\n")
	if got := string(renderUserConfig(o.userConfig)); got != want {
		t.Fatalf("rendered config:\n%s\nwant:\n%s", got, want)
	}
}

func TestWithConfigFileLaterFilesOverrideKeys(t *testing.T) {
	base := writeUserConfig(t, "[global]\nmgr_stats_period = 2\n[osd]\nosd_memory_target = 1073741824\n")
	override := writeUserConfig(t, "[osd]\nosd memory target = 805306368\nosd_op_num_shards = 1\n[mon]\nmon_osd_down_out_interval = 30\n")
	var o options
	for _, path := range []string{base, override} {
		if err := WithConfigFile(path)(&o); err != nil {
			t.Fatal(err)
		}
	}
	want := "[global]\nmgr_stats_period = 2\n[osd]\nosd_memory_target = 805306368\nosd_op_num_shards = 1\n[mon]\nmon_osd_down_out_interval = 30\n"
	if got := string(renderUserConfig(o.userConfig)); got != want {
		t.Fatalf("rendered config:\n%s\nwant:\n%s", got, want)
	}
}

func TestWithConfigFileRejectsUnsafeInput(t *testing.T) {
	for name, test := range map[string]struct{ content, want string }{
		"before section":   {"mgr_stats_period = 2\n", "before any [section]"},
		"missing value":    {"[global]\nmgr_stats_period\n", "expected key = value"},
		"bad section":      {"[global\nx = 1\n", "invalid section header"},
		"nested section":   {"[a]b]\nx = 1\n", "invalid section header"},
		"bad key":          {"[global]\nmgr.stats = 1\n", "invalid key"},
		"duplicate key":    {"[osd]\nosd_memory_target = 1\nosd-memory-target = 2\n", "duplicate [osd] osd_memory_target"},
		"include":          {"[global]\n!include /etc/other.conf\n", "include directives"},
		"include key":      {"[global]\ninclude = /etc/other.conf\n", "include is not supported"},
		"continuation":     {"[global]\nmgr_stats_period = 2 \\\n", "continuations"},
		"quoted comment":   {"[global]\nfoo = \"a;b\"\n", "ambiguous quoting"},
		"unbalanced quote": {"[global]\nfoo = \"a\n", "ambiguous quoting"},
		"fsid":             {"[global]\nfsid = 00000000-0000-0000-0000-000000000001\n", "fsid is generated by the fixture"},
		"mon host":         {"[global]\nmon host = 10.0.0.1\n", "mon_host is managed"},
		"pool size":        {"[global]\nosd pool default size = 3\n", "use WithPoolDefaults"},
		"crush rule":       {"[global]\nosd_pool_default_crush_rule = 1\n", "use WithDefaultCRUSHRoot"},
		"block size":       {"[osd]\nbluestore_block_size = 1\n", "use WithOSDBlockSize"},
		"auth":             {"[global]\nauth_client_required = none\n", "Cephx setup"},
		"messenger mode":   {"[global]\nms_mon_client_mode = secure\n", "use WithMessengerMode"},
		"messenger bind":   {"[global]\nms_bind_ipv6 = true\n", "WithHostNetwork"},
		"logging":          {"[global]\nlog_to_stderr = false\n", "container output"},
		"keyring":          {"[client.admin]\nkeyring = /tmp/k\n", "Cephx setup"},
		"rgw command line": {"[client]\nrgw frontends = beast port=1\n", "RGW command line"},
		"mds command line": {"[mds]\nmds_cache_memory_limit = 1\n", "MDS command line"},
		"nul":              {"[global]\nx = \x00\n", "NUL-free UTF-8"},
		"invalid utf8":     {"[global]\nx = \xff\n", "NUL-free UTF-8"},
		"oversized":        {"[global]\nx = " + strings.Repeat("a", userConfigMaxBytes) + "\n", "exceeds"},
	} {
		t.Run(name, func(t *testing.T) {
			var o options
			err := WithConfigFile(writeUserConfig(t, test.content))(&o)
			if err == nil || !strings.Contains(err.Error(), test.want) {
				t.Fatalf("WithConfigFile error = %v, want %q", err, test.want)
			}
			if o.userConfig != nil {
				t.Fatal("rejected file changed options")
			}
		})
	}
	var o options
	if err := WithConfigFile(filepath.Join(t.TempDir(), "missing.conf"))(&o); err == nil || !strings.Contains(err.Error(), "read Ceph config file") {
		t.Fatalf("missing file error = %v", err)
	}
}

func TestWithConfigFileBoundsMergedSize(t *testing.T) {
	half := strings.Repeat("a", userConfigMaxBytes/2)
	var o options
	if err := WithConfigFile(writeUserConfig(t, "[global]\nfirst = "+half+"\n"))(&o); err != nil {
		t.Fatal(err)
	}
	err := WithConfigFile(writeUserConfig(t, "[global]\nsecond = "+half+"\n"))(&o)
	if err == nil || !strings.Contains(err.Error(), "merged Ceph config files exceed") {
		t.Fatalf("merged size error = %v", err)
	}
	if len(o.userConfig) != 1 || len(o.userConfig[0].entries) != 1 {
		t.Fatalf("rejected merge changed options: %+v", o.userConfig)
	}
}

// The MON bootstrap must place user entries inside the generated sections and
// drop generated duplicates, since Ceph keeps the first value for a key. The
// result must stay acceptable to the fixture's later MON host and FSID readers.
func TestMonitorBootstrapMergesUserConfig(t *testing.T) {
	var o options
	if err := WithConfigFile(writeUserConfig(t, "[osd]\nosd_memory_target = 1073741824\n[global]\nmgr_stats_period = 5\n[client.admin]\nrgw_enable_usage_log = true\n"))(&o); err != nil {
		t.Fatal(err)
	}
	config, _ := runEmbeddedScript(t, "mon", map[string]string{
		"CEPH_FSID": "6f1b2c50-8b39-4c39-a0b1-6d4f55e1a3c2", "CEPH_OSD_BLOCK_SIZE": "1073741824",
	}, map[string][]byte{userConfigPath: renderUserConfig(o.userConfig)})
	sections := map[string][]string{}
	var current string
	for _, line := range strings.Split(config, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "[") {
			current = line
			if _, ok := sections[current]; ok {
				t.Fatalf("section %s repeated:\n%s", current, config)
			}
			sections[current] = nil
			continue
		}
		if key, value, ok := strings.Cut(line, "="); ok {
			sections[current] = append(sections[current], normalizeConfigKey(key)+"="+strings.TrimSpace(value))
		}
	}
	for section, want := range map[string]string{
		"[osd]":          "osd_memory_target=1073741824",
		"[global]":       "mgr_stats_period=5",
		"[client.admin]": "rgw_enable_usage_log=true",
	} {
		key, _, _ := strings.Cut(want, "=")
		var values []string
		for _, entry := range sections[section] {
			if strings.HasPrefix(entry, key+"=") {
				values = append(values, entry)
			}
		}
		if len(values) != 1 || values[0] != want {
			t.Fatalf("%s %s entries = %v, want only %s:\n%s", section, key, values, want, config)
		}
	}
	if !strings.Contains(config, "osd pool default pg num = 8\n") || !strings.Contains(config, "bluestore cache size = 67108864\n") {
		t.Fatalf("generated settings without user overrides were lost:\n%s", config)
	}
	if fsid, err := monitorConfigClusterIdentity([]byte(config)); err != nil || fsid != "6f1b2c50-8b39-4c39-a0b1-6d4f55e1a3c2" {
		t.Fatalf("merged config identity = %q, %v", fsid, err)
	}
	if _, err := replaceGlobalMonitorHost([]byte(config), "[v2:192.0.2.13:3300]"); err != nil {
		t.Fatalf("merged config cannot refresh MON host: %v", err)
	}
	if _, err := defaultCRUSHRuleConfig([]byte(config), "1"); err != nil {
		t.Fatalf("merged config cannot select CRUSH rule: %v", err)
	}
}

func TestMonitorBootstrapWithoutUserConfigIsUnchanged(t *testing.T) {
	env := map[string]string{"CEPH_FSID": "6f1b2c50-8b39-4c39-a0b1-6d4f55e1a3c2", "CEPH_OSD_BLOCK_SIZE": "1073741824"}
	config, _ := runEmbeddedScript(t, "mon", env, nil)
	if strings.Contains(config, "ceph.conf.merged") || !strings.HasPrefix(config, "[global]\nfsid = 6f1b2c50-8b39-4c39-a0b1-6d4f55e1a3c2\n") {
		t.Fatalf("unexpected generated config:\n%s", config)
	}
}
