// Code generated by internal/facadegen. DO NOT EDIT.

package cephfs

import (
	"context"

	"github.com/jsyoo5b/ceph-testcontainers-go/ceph"
	"github.com/jsyoo5b/ceph-testcontainers-go/internal/cluster"
	"github.com/jsyoo5b/ceph-testcontainers-go/internal/multicluster"
	"github.com/testcontainers/testcontainers-go"
)

const (
	PinExport      = cluster.CephFSPinExport
	PinDistributed = cluster.CephFSPinDistributed
	PinRandom      = cluster.CephFSPinRandom
)

// Config creates one named filesystem with dedicated pools and MDS
// daemons. Name defaults to tc-cephfs, ActiveMDS to one, and StandbyMDS to zero.
// Omitted pool names become <Name>-metadata and <Name>-data. Metadata and the
// default data pool must be replicated; additional pools may use erasure coding
// with AllowOverwrites. Each pool defaults to application=cephfs. Directory
// layouts select additional pools after filesystem creation. StandbyReplay
// assigns up to one journal follower per active rank; extra standbys stay idle.
type Config = cluster.CephFSConfig

// MDS is an owned metadata daemon. ID is its static Ceph daemon name;
// MDSStatus reports its current rank and GID. Stop/Start can inject failures.
// Cluster termination removes stopped and partially initialized daemons too.
type MDS = cluster.MDSContainer

// Filesystem describes one filesystem and embeds its first MDS container
// for compatibility with Start. MDSs exposes every owned metadata daemon.
// The cluster owns their lifetime. Clients use libcephfs through WithClient
// without a kernel or FUSE mount on the host.
type Filesystem = cluster.CephFSContainer

// MDSStatus records a metadata daemon's current native FSMap identity. GID
// changes after process restart. Ordinary standbys have rank -1; replay standbys
// follow the rank they would replace. Owned identifies this fixture's daemons.
type MDSStatus = cluster.MDSStatus

// FilesystemStatus contains active ranks and this fixture's ordinary/replay
// standbys. Standbys belonging to another filesystem are never counted.
type FilesystemStatus = cluster.CephFSMDSStatus

// SubvolumeAuthorizationConfig creates a fresh Cephx principal. Access
// must be "r" or "rw". Namespace-isolated subvolumes are required: a path cap
// alone cannot restrict direct RADOS access to the subvolume's file data.
type SubvolumeAuthorizationConfig = cluster.CephFSSubvolumeAuthorizationConfig

// SubvolumeAuthorization describes an owned native volumes grant. Client
// provides credentials for WithClientIdentity and independent Linux clients.
// Exported fields are descriptions; changing them cannot redirect mutations.
// Copies share grant/deauthorization state. The namespace cap covers the entire
// actual namespace, which may be shared by clones inheriting a source layout.
type SubvolumeAuthorization = cluster.CephFSSubvolumeAuthorization

// SubvolumeAuthorizedClient is one entry in native authorized_list. This
// is volumes metadata, not a complete audit of independently edited Cephx caps.
type SubvolumeAuthorizedClient = cluster.CephFSSubvolumeAuthorizedClient

// DataPoolState reports a currently registered native filesystem data
// pool. ID distinguishes a pool recreated under the same name. Default marks
// the immutable first data pool, which also stores inode backtraces.
type DataPoolState = cluster.CephFSDataPoolState

// DataPool identifies an additional pool attached by AddDataPool. Its
// private identity and state are shared by copied handles. Exported fields are
// descriptive; editing them does not redirect removal to another pool.
type DataPool = cluster.CephFSDataPool

// PinType selects one native directory policy. Policies can coexist;
// ancestry and Ceph's native precedence determine actual subtree placement.
type PinType = cluster.CephFSPinType

// PinSetting changes one policy field. Export accepts an integer owned
// active rank, or -1 to remove the local pin. Distributed accepts 0 or 1.
// Random accepts a probability in [0,1], additionally capped by the MDS's
// mds_export_ephemeral_random_max. Ephemeral feature configuration is caller-
// controlled; setting a policy does not prove its runtime effect.
type PinSetting = cluster.CephFSPinSetting

// PinPolicy reports the local virtual xattrs on the directory targeted by
// the native volumes pin command. For subvolumes, Path is the base directory,
// one level above the UUID data directory returned by SubvolumeInfo. ExportRank
// -1, Distributed false and RandomProbability 0 are native virtual defaults.
// These local values do not report inherited policy or actual MDS authority.
// RandomProbability has the precision of native virtual-xattr text.
type PinPolicy = cluster.CephFSPinPolicy

// PinOverride owns a temporary change to one confirmed owned resource's
// policy field. Copies share restoration state. Retain a non-nil result even
// on error: cancellation or a lost reply can leave native state changed.
// Explicit Restore returns that field to its prior canonical virtual value;
// other fields, directories and data are preserved. It refuses a different
// current field or native resource identity. Same-value outside edits and
// changes below native text precision cannot be distinguished; do not race
// external pin edits or delete/recreate the directory while the handle is used.
type PinOverride = cluster.CephFSPinOverride

// QuiesceConfig bounds reaching the I/O pause and its lifetime. Both
// durations must be at least one second. Expiration is a native safety timer;
// observing ceph.Status does not extend it. This fixture does not pause processes.
type QuiesceConfig = cluster.CephFSQuiesceConfig

// QuiesceState describes one native set. Version changes on native state
// transitions or edits. Members are native file: paths, not mutable handle fields.
type QuiesceState = cluster.CephFSQuiesceState

// Quiesce owns a newly created, unique native quiesce set. Copies share
// state. Release confirms the captured QUIESCED version, so an outside edit or
// expiration cannot masquerade as a consistent checkpoint. An uncertain create
// may return a non-nil handle plus an error; retain it or let its native timer
// expire before terminating the cluster. Never externally edit this set ID.
type Quiesce = cluster.CephFSQuiesce

// SessionTimeouts are the filesystem's MDSMap client session limits.
// A silent client whose capabilities nobody wants stays open until Autoclose.
// Once another client asks for its capabilities, the MDS evicts it as soon as
// Timeout passes. With Ceph's default mds_session_blocklist_on_timeout the
// evicted address is blocklisted. These are filesystem settings, not central
// configuration, so TemporaryConfig cannot change them. Native values are
// whole seconds.
type SessionTimeouts = cluster.CephFSSessionTimeouts

// Session is one client session reported by an active MDS rank. A client
// with sessions on several ranks appears once per rank. Address is the
// session's IP:port/nonce, the same form BlocklistEntries reports, so an
// evicted session can be matched to its blocklist entry. EntityID, Hostname,
// Root and PID come from the metadata the client sent when it opened the
// session.
type Session = cluster.CephFSSession

// SessionTimeoutsOverride owns one temporary change to both session
// limits of a filesystem. Copies share restoration state. Retain a non-nil
// result even on error: a lost reply can leave either value changed.
type SessionTimeoutsOverride = cluster.CephFSSessionTimeoutsOverride

// SubvolumeSnapshot is an owned snapshot of a confirmed subvolume. Its
// public fields describe creation; mutations use the captured private identity.
// Snapshot creation does not quiesce concurrent application writers.
type SubvolumeSnapshot = cluster.CephFSSubvolumeSnapshot

// SnapshotPendingClone identifies a native clone still using a snapshot.
// An empty GroupName selects the default group.
type SnapshotPendingClone = cluster.CephFSSnapshotPendingClone

// SubvolumeSnapshotInfo contains current native snapshot metadata. Path
// identifies the frozen data directory, including Ceph's incarnation UUID.
type SubvolumeSnapshotInfo = cluster.CephFSSubvolumeSnapshotInfo

// CloneConfig names a new clone in an existing group. DataPool optionally
// overrides the snapshot's data pool. Ceph copies the snapshot's quota and
// layout; with a DataPool override it clears the inherited RADOS namespace.
// Quota and namespace changes are deliberately not part of the clone request.
type CloneConfig = cluster.CephFSCloneConfig

// SubvolumeClone is an asynchronous, owned clone request. WaitForSubvolumeClone
// returns a usable subvolume only after native cloning completes. A non-nil
// descriptor on error records the attempted request but cannot be adopted or
// canceled automatically. Cluster cleanup removes incomplete data too.
type SubvolumeClone = cluster.CephFSSubvolumeClone

// SubvolumeCloneStatus reports native pending, in-progress, complete,
// failed or canceled state. FailureErrno is zero when no native failure was
// recorded. Source fields are normally absent after successful completion.
type SubvolumeCloneStatus = cluster.CephFSSubvolumeCloneStatus

// SubvolumeGroupConfig creates a named group inside an existing filesystem.
// SizeBytes is its aggregate directory quota; zero leaves it unlimited. DataPool
// optionally selects one of the filesystem's existing data pools. These helpers
// do not create pools, filesystems, MDS daemons or orchestrator services.
type SubvolumeGroupConfig = cluster.CephFSSubvolumeGroupConfig

// SubvolumeConfig creates a directory tree managed by the MGR volumes
// module. An empty GroupName selects Ceph's default group. Zero SizeBytes leaves
// it unlimited. DataPool selects an existing filesystem data pool; empty inherits
// the group's layout. NamespaceIsolated gives file data a separate RADOS
// namespace; client access still requires appropriate Cephx capabilities.
type SubvolumeConfig = cluster.CephFSSubvolumeConfig

// SubvolumeGroup is an owned group returned by CreateSubvolumeGroup.
// Public fields are creation-time descriptions; mutations use the private
// identity captured after successful creation. Get current quota through
// SubvolumeGroupInfo. Removing a group requires it to be empty.
type SubvolumeGroup = cluster.CephFSSubvolumeGroup

// Subvolume is an owned subvolume returned by CreateSubvolume. Its public
// fields describe creation. SubvolumeInfo queries current native state. Remove
// deletes this directory tree and its contents, preserving its filesystem and
// pools; native trash purging is asynchronous.
type Subvolume = cluster.CephFSSubvolume

// SubvolumeGroupInfo reports native group metadata. QuotaBytes is zero for
// an unlimited quota. BytesUsed is Ceph's directory size accounting, which can
// lag recent writes. CreatedAt is the directory birth time used by the native
// volumes module.
type SubvolumeGroupInfo = cluster.CephFSSubvolumeGroupInfo

// SubvolumeInfo reports a native subvolume, including its real mount path
// and RADOS namespace. Read-only queries also describe resources created outside
// these helpers, but those resources cannot be resized or removed through an
// owned handle. QuotaBytes is zero for unlimited.
type SubvolumeInfo = cluster.CephFSSubvolumeInfo

// WithFilesystems creates named filesystems and their MDS topologies during ceph.Run.
// No arguments selects the default filesystem. Repeated options replace the
// list; Start can add further filesystems after ceph.Run returns.
func WithFilesystems(configs ...Config) ceph.Option {
	return cluster.WithCephFS(configs...)
}

// WithMDSImage selects the metadata server image used by Start.
// If omitted, MDS uses the image passed to ceph.Run. Use matching Ceph versions.
func WithMDSImage(image string) ceph.Option {
	return cluster.WithMDSImage(image)
}

// Start creates one filesystem with dedicated pools and its
// ActiveMDS+StandbyMDS daemons on an existing cluster. A zero config selects
// the default filesystem tc-cephfs with one active MDS named a. Every pool and
// OSD placement is validated before mutations. Existing filesystems are
// rejected instead of modified. Creating a second filesystem enables Ceph's
// global enable_multiple flag; the existing filesystem and its configuration
// are preserved.
//
// Customizers apply to each MDS and must preserve its identity, config, keyring,
// entrypoint and networking. A non-nil result with an error identifies attempted
// resources; the cluster owns cleanup, including partial daemon startup.
func Start(ctx context.Context, c *ceph.Container, config Config, opts ...testcontainers.ContainerCustomizer) (*Filesystem, error) {
	return cluster.StartCephFS(ctx, c, config, opts...)
}

// Filesystems returns the cluster's owned filesystem descriptors sorted by
// filesystem name, including a descriptor whose setup partially failed. The
// cluster owns their MDS containers.
func Filesystems(c *ceph.Container) []*Filesystem {
	return cluster.Filesystems(c)
}

// Remove deletes an owned filesystem: it fails and removes it in the
// FSMap, terminates its MDS daemons, deletes their Cephx keys and removes the
// metadata, default data and AdditionalDataPools that its configuration
// created, together with their CRUSH rules and EC profiles. Pools attached
// later with AddDataPool are detached but kept; remove them with RemovePool.
// File data in the removed pools is destroyed. Stop clients, CephFS mirrors
// and subvolume operations on the filesystem first; their handles fail
// afterwards. A retry after an error continues with whatever remains.
func Remove(ctx context.Context, c *ceph.Container, name string) error {
	return cluster.RemoveCephFS(ctx, c, name)
}

// MirrorConfig connects existing CephFS filesystems. The caller creates
// both clusters and their MDS/filesystems before starting snapshot mirroring.
type MirrorConfig = multicluster.CephFSMirrorConfig

// MirrorDaemon is one owned mirror process. DaemonName is a stable fixture
// identity; the native instance identity is its authenticated client GID.
// All daemons in a fixture share SourceClientEntity and the same peer policy.
type MirrorDaemon = multicluster.CephFSMirrorDaemon

// Mirror owns its daemons and network attachments added to source MGR
// candidates. Its embedded ceph.Container is the initial daemon, and becomes nil
// after that daemon is removed. Use Daemons for the current topology. It does not own
// either Ceph cluster or the filesystems' data.
type Mirror = multicluster.CephFSMirror

// RunMirror configures one-way directory snapshot mirroring between two
// existing filesystems and starts each initial cephfs-mirror in a separate
// container. NoInitialDaemons retains setup without launching a daemon. image
// must meet the control or all role requirements, including cephfs-mirror and
// the ceph CLI used to query its local admin socket. MGRs must supply mirroring.
// A non-nil result returned with an error must be terminated for partial cleanup.
// Terminate leaves Ceph auth, peer and directory policies in the caller-owned
// disposable clusters; it does not undo configuration or delete mirrored data.
// Both clusters must use the same network mode. Host mode requires no extra
// daemon or manager attachment; bridge mode joins the peer cluster network.
// Initial daemon names are a through z, then node-27 and onward.
func RunMirror(ctx context.Context, image string, config MirrorConfig, opts ...testcontainers.ContainerCustomizer) (*Mirror, error) {
	return multicluster.RunCephFSMirror(ctx, image, config, opts...)
}

// MirrorDirectoryAddition retains one explicit addition intent. It owns
// no cluster, daemon, directory, data or cleanup hook. A nonnil receipt returned
// with an error retains an uncertain request; repeat BeginDirectoryAddition with
// the same path and a fresh context. Only one pending intent is admitted.
type MirrorDirectoryAddition = multicluster.CephFSMirrorDirectoryAddition

// MirrorDirectoryAdditionStatus reports native policy presence in the
// retained original scope. Registered also requires this receipt's published
// owned generation. Neither flag proves daemon assignment or snapshot replay.
type MirrorDirectoryAdditionStatus = multicluster.CephFSMirrorDirectoryAdditionStatus

// MirrorDirectoryRemoval retains an explicit path removal and its original
// live daemon/peer cohort. It owns no cluster, container, directory or cleanup.
// A non-nil receipt returned with an error retains an uncertain native request;
// retry BeginDirectoryRemoval for the same path with a fresh context.
type MirrorDirectoryRemoval = multicluster.CephFSMirrorDirectoryRemoval

// MirrorDirectoryRemovalStatus observes the original path registration.
// Released proves every original replayer has no registered sync cycle for the
// directory in its original normal session. It does not establish worker thread
// exit, successful remote unlock, checkpoint completion or unchanged metadata.
type MirrorDirectoryRemovalStatus = multicluster.CephFSMirrorDirectoryRemovalStatus

type MirrorDirectoryRemovalDaemonStatus = multicluster.CephFSMirrorDirectoryRemovalDaemonStatus

// MirrorSnapshot identifies a source snapshot reported by the native
// receiving peer. ID is the original source snap ID, not the destination ID.
type MirrorSnapshot = multicluster.CephFSMirrorSnapshot

// MirrorDirectoryStatus observes one current owned directory policy.
// MappingState is MGR assignment state; State is the selected daemon's native
// idle/syncing/failed replay state. Ready proves a live owned assignment and
// active peer for this directory, not whole-fixture health, data equivalence or
// an application checkpoint. DaemonProblems reports other unavailable members.
// Native counters reset on daemon restart/directory reassignment.
type MirrorDirectoryStatus = multicluster.CephFSMirrorDirectoryStatus

// MirrorPeerRemoval retains one explicit removal and its original live
// daemon cohort. It owns no clusters, containers, policy, data or cleanup hooks.
// A non-nil handle returned with an error retains an uncertain native request;
// retry BeginPeerRemoval with the same UUID and a fresh context to reconcile it.
type MirrorPeerRemoval = multicluster.CephFSMirrorPeerRemoval

// MirrorPeerRemovalStatus describes one observation of the original UUID.
// Drained means every witnessed original live replayer finished native teardown
// in the same process/filesystem session. It does not establish snapshot
// completion, remote lock release, or unchanged destination metadata.
type MirrorPeerRemovalStatus = multicluster.CephFSMirrorPeerRemovalStatus

type MirrorPeerRemovalDaemonStatus = multicluster.CephFSMirrorPeerRemovalDaemonStatus

// MirrorProcessBindingStatus is a local snapshot of optional capability.
// State contains a finite reason; factory errors and endpoint bodies are omitted.
type MirrorProcessBindingStatus = multicluster.CephFSMirrorProcessBindingStatus

// MirrorProcessQuiescenceStatus is original-cohort evidence only.
// It does not assert graceful teardown, current fixture silence, successful
// remote unlock, irreversibility against checkpoint restore, Drained or Released.
type MirrorProcessQuiescenceStatus = multicluster.CephFSMirrorProcessQuiescenceStatus

// MirrorOriginalProcessStatus retains one original run and watcher.
// New runs and unrelated watchers never replace these receipt identities.
type MirrorOriginalProcessStatus = multicluster.CephFSMirrorOriginalProcessStatus

// MirrorProcessQuiescenceAcknowledgment is the result of one explicit
// acceptance attempt. Acknowledged is true only when this invocation freshly
// proved every original container removed and committed the separate terminal
// decision. Observation is never cached evidence. A failed retry does not undo
// an earlier private decision, but returns Acknowledged=false for that attempt.
type MirrorProcessQuiescenceAcknowledgment = multicluster.CephFSMirrorProcessQuiescenceAcknowledgment
