// Code generated by internal/facadegen. DO NOT EDIT.

package rbd

import (
	"context"
	"io"

	"github.com/jsyoo5b/ceph-testcontainers-go/ceph"
	"github.com/jsyoo5b/ceph-testcontainers-go/internal/cluster"
	"github.com/jsyoo5b/ceph-testcontainers-go/internal/multicluster"
	"github.com/testcontainers/testcontainers-go"
)

const (
	MirrorModeSnapshot = multicluster.RBDMirrorModeSnapshot
	MirrorModeJournal  = multicluster.RBDMirrorModeJournal
	MirrorScopeImage   = multicluster.RBDMirrorScopeImage
	MirrorScopePool    = multicluster.RBDMirrorScopePool
)

// Namespace identifies an image namespace created by this cluster. Names and
// native pool identity are immutable. Namespace removal never deletes images,
// snapshots or trash; callers must remove those through their RBD client first.
// The cluster disposes of namespaces with all its data when it terminates.
type Namespace = cluster.RBDNamespace

// InitPool initializes an existing replicated pool for RBD metadata. Pools
// registered to other applications are rejected; no force option is used. An
// existing RBD initialization is safe to repeat. EC pools may supply image data
// but cannot hold RBD metadata. Create the pool first, then wait for clean PGs
// before client I/O. Partial initialization never deletes pool data.
func InitPool(ctx context.Context, c *ceph.Container, pool string) error {
	return cluster.InitRBDPool(ctx, c, pool)
}

// CreateNamespace creates a fresh image namespace in an initialized,
// replicated RBD pool. Existing names are rejected without changing their data.
// A non-nil descriptor returned with an error identifies an attempted creation,
// but cannot authorize removal unless creation was confirmed. Inspect native
// state or dispose of the cluster after an uncertain creation failure.
func CreateNamespace(ctx context.Context, c *ceph.Container, pool, name string) (*Namespace, error) {
	return cluster.CreateRBDNamespace(ctx, c, pool, name)
}

// ListNamespaces returns the pool's native namespace names in sorted order,
// including names created outside this fixture. The unnamed default namespace
// is omitted by Ceph. Listing does not grant ownership for removal.
func ListNamespaces(ctx context.Context, c *ceph.Container, pool string) ([]string, error) {
	return cluster.ListRBDNamespaces(ctx, c, pool)
}

// RemoveNamespace removes a confirmed namespace owned by this cluster. Ceph
// refuses nonempty namespaces, including images in trash. No image purge or
// force option is used. Successful removal is idempotent; failed CLI removal
// can be retried with the same descriptor and a new context. Replacing its
// underlying pool is rejected. Do not delete and recreate the same named
// namespace through another client while its descriptor is in use: native RBD
// namespaces have no separate generation identity to distinguish replacements.
func RemoveNamespace(ctx context.Context, c *ceph.Container, ns *Namespace) error {
	return cluster.RemoveRBDNamespace(ctx, c, ns)
}

// WithPools creates replicated pools for RBD images during ceph.Run and
// initializes their RBD metadata. Application defaults to rbd and must not be
// another application; erasure-coded data pools are created with ceph.WithPools and
// referenced as an image's data pool. Repeated options replace the list.
func WithPools(configs ...ceph.PoolConfig) ceph.Option {
	return cluster.WithRBDPools(configs...)
}

// MirrorMode selects the per-image replication mechanism, independently of
// the pool/namespace scope. Image scope enables images explicitly; pool scope
// automatically enrolls images carrying the journaling feature.
type MirrorMode = multicluster.RBDMirrorMode

// MirrorConfig connects two existing clusters through destination-side
// rbd-mirror daemons. Both clusters must already contain an initialized RBD ceph.Pool.
// SourceSite and DestinationSite default to "source" and "destination".
type MirrorConfig = multicluster.RBDMirrorConfig

// Mirror owns its daemons and setup CLI containers, not the Ceph clusters.
// The embedded ceph.Container is the initial daemon's compatibility handle. Its
// Stop and Start affect only that daemon. Removing it clears the handle without
// assigning another daemon. Use Daemons for current membership. Terminate
// removes all owned runtime containers, including partially created or
// previously removed daemons.
type Mirror = multicluster.RBDMirror

// MirrorDaemon is one destination-side rbd-mirror process. Every daemon has
// a distinct Ceph user; receiving peer credentials remain in the destination's
// config-key store. Stop and Start retain its identity and native pool state.
type MirrorDaemon = multicluster.RBDMirrorDaemon

// MirrorDaemonStatus is the native daemon admin socket's pool membership and
// election state. A running container can report no pool replayers until Ceph
// completes discovery; callers must inspect the intended pool and peer.
type MirrorDaemonStatus = multicluster.RBDMirrorDaemonStatus

// MirrorPoolReplayerStatus describes one pool/peer replayer. Image replay is
// distributed among instances; being a pool leader does not mean replaying all
// images locally.
type MirrorPoolReplayerStatus = multicluster.RBDMirrorPoolReplayerStatus

// RunMirror enables the selected scope on both pool/namespaces, imports a receiving
// peer into the destination, and starts the configured initial daemons connected
// to both clusters. NoInitialDaemons retains setup without launching a daemon.
// A new peer is rx-only; an existing tx-only peer becomes rx-tx so creating a
// reverse link preserves the transmission already used by the first link.
// image must meet the control or all role requirements, including the rbd and
// ceph CLIs, rbd-mirror and the common utilities. It supplies both setup clients
// and mirror daemon containers. Enable each intended source
// image through EnableImage or the RBD CLI in image scope. ceph.Pool scope
// automatically enrolls journal-enabled images. Snapshot images need subsequent
// mirror checkpoints; journal images replay writes without mirror snapshots.
//
// The caller must Terminate a non-nil result even when setup returns an error.
// Terminate removes runtime containers but leaves mirroring mode, peer and auth
// configuration in the disposable clusters; it never destroys pools or data.
// Customizers apply to the daemon only and must preserve its networking, Ceph
// configuration, credentials and entrypoint.
// Both clusters must use the same network mode. Host-mode clusters share the
// Docker host namespace; bridge-mode daemons attach to both cluster networks.
// Initial daemon names are a through z, then node-27 and onward. A process's
// socket readiness does not guarantee pool discovery or leader convergence;
// query the daemon ceph.Status for native election state.
// Named namespace setup initializes a disabled default namespace as init-only,
// preserving an existing active default policy. Existing target scope, remote
// namespace mapping and configured site names must match; this method does not
// silently reconfigure them. Site names are cluster-wide and must agree across
// links. External pool/namespace/mirror edits must not race setup; native named
// namespaces have no separate generation. Quiesce existing writers before
// enabling pool scope. PolicyStatus reports the current native mapping.
// Successful setup captures default/selected namespace mirror UUIDs, scopes and
// mappings. Later typed mutations reject replacement or changed policies.
func RunMirror(ctx context.Context, image string, config MirrorConfig, opts ...testcontainers.ContainerCustomizer) (*Mirror, error) {
	return multicluster.RunRBDMirror(ctx, image, config, opts...)
}

// ExportBackup writes a CLI-generated format-2 archive to destination. The
// archive includes image metadata and snapshots. No mirror daemon is required.
// The caller owns the writer and decides where to retain the backup.
func ExportBackup(ctx context.Context, client testcontainers.Container, image string, destination io.Writer) error {
	return multicluster.ExportRBDBackup(ctx, client, image, destination)
}

// ExportIncremental writes the CLI diff from fromSnapshot to image (which
// can include @snapshot). Restore requires the matching baseline snapshot.
func ExportIncremental(ctx context.Context, client testcontainers.Container, image, fromSnapshot string, destination io.Writer) error {
	return multicluster.ExportRBDIncremental(ctx, client, image, fromSnapshot, destination)
}

// RestoreBackup imports a format-2 archive into a new image on the client's
// own cluster. ceph.Pool creation and archive retention belong to the caller.
func RestoreBackup(ctx context.Context, client testcontainers.Container, image string, archive io.Reader) error {
	return multicluster.RestoreRBDBackup(ctx, client, image, archive)
}

// RestoreIncremental applies a CLI diff to an existing image. Ceph checks
// that its baseline snapshot exists; this function does not invent a baseline.
func RestoreIncremental(ctx context.Context, client testcontainers.Container, image string, archive io.Reader) error {
	return multicluster.RestoreRBDIncremental(ctx, client, image, archive)
}

// MirrorImageStatus is a read-only observation of the image in this link's
// selected source and destination namespaces. State, Description and LastUpdate
// are the destination's native local status, not its remote peer status.
// ReplayReady means an owned receiving process is currently replaying this
// source-primary/destination-secondary pair. It proves neither completion of a
// particular write nor completion of a mirror snapshot. Verify application data
// or the application's explicit checkpoint separately.
type MirrorImageStatus = multicluster.RBDMirrorImageStatus

// MirrorScope selects explicit image enrollment or automatic journal-image
// enrollment for one pool/namespace. It is separate from snapshot/journal Mode.
type MirrorScope = multicluster.RBDMirrorScope

// MirrorNamespaceState reports native policy for a selected pool/namespace.
// An empty Namespace/RemoteNamespace identifies the actual default namespace.
// Mode is disabled, init-only, image or pool. MirrorUUID is a native mirroring
// identity, not the cluster FSID. A configured policy alone proves no replication.
type MirrorNamespaceState = multicluster.RBDMirrorNamespaceState

// MirrorPolicies reports both current native policies. Readback does not
// adopt ownership of namespaces or permit their deletion.
type MirrorPolicies = multicluster.RBDMirrorPolicies

// MirrorNamespace is a retained read-only binding of already configured
// namespace policies to one Mirror's original pool, peer and owned cohort.
// It owns no resources and has no independent daemon or cleanup lifecycle.
// An actual owner Rebootstrap attempt invalidates this binding permanently;
// after successful Rebootstrap explicitly BindNamespace again for a new view.
type MirrorNamespace = multicluster.RBDMirrorNamespace

// MirrorReceiverStatus observes the selected pool/namespace and an exact
// owned receiver cohort. Ready means scope discovery and native leader/member
// agreement, including an owned leader. It requires no mirrored image and
// proves neither image replay nor delivery of a particular write/checkpoint.
// ForeignInstances makes the exact-cohort predicate false; it does not mean
// that another fixture sharing the receiving pool is unhealthy.
type MirrorReceiverStatus = multicluster.RBDMirrorReceiverStatus

// MirrorReceiverDaemonStatus is one current owned receiver's selected native
// pool/peer and namespace discovery, not an aggregate image replay state.
type MirrorReceiverDaemonStatus = multicluster.RBDMirrorReceiverDaemonStatus
