// Code generated by internal/facadegen. DO NOT EDIT.

package rgw

import (
	"context"

	"github.com/jsyoo5b/ceph-testcontainers-go/ceph"
	"github.com/jsyoo5b/ceph-testcontainers-go/internal/cluster"
	"github.com/jsyoo5b/ceph-testcontainers-go/internal/multicluster"
	"github.com/testcontainers/testcontainers-go"
)

const (
	SyncAllowed   = multicluster.RGWSyncAllowed
	SyncEnabled   = multicluster.RGWSyncEnabled
	SyncForbidden = multicluster.RGWSyncForbidden
)

// WithGateways starts named gateways during ceph.Run. No arguments starts one default
// gateway. Repeated options replace the list. All gateways share this cluster's
// backing zone; multisite scope is configured separately by multicluster APIs.
func WithGateways(configs ...Config) ceph.Option {
	return cluster.WithRGW(configs...)
}

// WithImage selects the image used by gateways started with Start.
// If omitted, RGW uses the image passed to ceph.Run. Use matching Ceph versions.
func WithImage(image string) ceph.Option {
	return cluster.WithRGWImage(image)
}

// Gateway is an optional S3 gateway owned by its Ceph cluster. AccessKey
// and SecretKey belong to a generated ordinary S3 user for trusted tests.
type Gateway = cluster.RGWContainer

// Config selects a gateway instance and optional native RGW multisite scope.
// Name defaults to default; different names allow multiple gateways in one zone.
// Realm, Zonegroup and Zone must already exist when supplied. Region defaults to
// us-east-1. SkipUserCreation is useful when sharing existing S3 credentials or
// configuring multisite users through radosgw-admin.
type Config = cluster.RGWConfig

// UserConfig describes a new S3 identity. Empty ID generates a unique ID;
// DisplayName defaults to Testcontainers. AdminCaps is an explicit native
// expression such as "users=read;usage=read" for the RGW Admin Ops REST API.
// Neither the global admin nor the multisite system flag is granted. MaxBuckets
// nil preserves Ceph's default; zero allows unlimited buckets and -1 forbids
// creating buckets. Tenant selects a native namespace; empty preserves the
// legacy namespace. ID is the local user ID, without a tenant prefix.
type UserConfig = cluster.RGWUserConfig

// User is an identity created through a gateway. Credentials are returned
// explicitly by Credentials; formatting this handle never includes secrets.
// Users remain in Ceph when a gateway is removed, until explicitly removed or
// the disposable cluster is terminated. Use another gateway in the same scope
// for an owned user's operations if the original gateway has been removed.
type User = cluster.RGWUser

// Quota uses bytes, matching modern radosgw-admin output. For each limit,
// -1 disables that limit; zero is an actual zero limit. Enabled controls whether
// the configured limits are enforced. Native RGW quota caches and asynchronous
// accounting can delay enforcement; reading this policy does not flush caches.
type Quota = cluster.RGWQuota

type AdminCapability = cluster.RGWAdminCapability

// UserInfo is a current native policy snapshot, deliberately excluding keys.
// BucketQuota applies individually to every bucket owned by this user.
// DefaultStorageClass preserves native representation: STANDARD on a named
// default placement is persisted and later read back as an empty string.
type UserInfo = cluster.RGWUserInfo

// StorageClassConfig maps one native S3 storage class to an existing data
// pool. STANDARD is required. Other class names, for example STANDARD_IA, must
// also be accepted by the consumer's S3 SDK. Data pools may be replicated or EC;
// RGW does not require EC overwrites because it writes complete objects.
type StorageClassConfig = cluster.RGWStorageClassConfig

// PlacementConfig adds a fresh, non-default bucket placement target. IndexPool
// and DataExtraPool must be existing replicated pools supporting omap. It never
// changes the zonegroup default or any existing bucket's immutable placement.
// InlineData nil preserves Ceph's true default; false separates object heads
// and data. Native external placement/topology edits must not race these helpers.
type PlacementConfig = cluster.RGWPlacementConfig

// Placement identifies a newly created native policy and its exact runtime
// scope. LocationConstraint can be passed to S3 CreateBucket. Creation stores
// configuration; ApplyPlacement restarts a standalone gateway or publishes a
// guarded realm period. Import that period into other clusters before explicitly
// activating their gateways with ReloadPlacement. Failed creation may return a
// partial handle for inspection; it is never rolled back by deleting pools,
// policies, buckets or data.
type Placement = cluster.RGWPlacement

// PlacementState is a native policy snapshot. DefaultPlacement is the
// zonegroup default, which these helpers never modify. Creation and activation
// do not assign any user's default placement or storage class.
type PlacementState = cluster.RGWPlacementState

// AccountConfig creates a new native account. Empty ID generates a unique
// RGW-prefixed 17-digit ID; Name defaults to a unique fixture name. Tenant is
// optional and isolates bucket names. Account IDs and email are globally unique.
// MaxBuckets nil preserves the native default. No user migration is performed.
type AccountConfig = cluster.RGWAccountConfig

// Account is a fresh account owned by this fixture. Its native metadata
// version tag distinguishes its lifetime from a deleted/recreated account.
// Copies share lifecycle state. Removing a gateway does not remove the account.
type Account = cluster.RGWAccount

// AccountInfo contains account-wide limits and the individual bucket policy.
// AccountQuota applies across all account users, buckets and roles, rather than
// to one user's storage. Quota readback does not flush native accounting caches.
type AccountInfo = cluster.RGWAccountInfo

// TLSConfig enables a native Beast HTTPS listener alongside HTTP. Supply
// a PEM certificate chain and matching unencrypted private key. No proxy is
// involved. Clients must explicitly trust its CA and use a matching hostname.
// Files live only in the owned RGW container; descriptors never log key bytes.
type TLSConfig = cluster.RGWTLSConfig

// UserUsage is a native storage-accounting snapshot, not dated request or
// bandwidth usage. Scope is "user" for an ordinary user and "account" for an
// account identity. OwnerID identifies that effective aggregation owner; account
// stats cover all of the account's users, roles and buckets, not only UserID.
// Native accounting updates asynchronously; this snapshot does not force sync,
// flush quota caches, prove quota enforcement or verify object content.
type UserUsage = cluster.RGWUserUsage

// UserPlacementConfig selects an owned placement as a user's default for
// future buckets. StorageClass defaults to STANDARD. Tags nil preserves the
// user's current placement tags; a nonempty list replaces them exactly. An
// explicitly empty list is unsupported by radosgw-admin and is rejected.
// Replace matching tags with nonmatching tags to revoke access to a restricted
// target. Placement tags authorize new bucket placement, not object access.
type UserPlacementConfig = cluster.RGWUserPlacementConfig

// Start starts an independently owned, named gateway on an existing
// cluster. A zero config starts the default gateway and creates its test user.
// Customizers are applied last; preserve the required command, network and
// listener settings. A non-nil result returned with an error remains owned by
// the cluster for cleanup.
func Start(ctx context.Context, c *ceph.Container, config Config, opts ...testcontainers.ContainerCustomizer) (*Gateway, error) {
	return cluster.StartRGW(ctx, c, config, opts...)
}

// Remove removes one owned gateway container. Zone configuration, S3 users,
// buckets and data remain available through other gateways or a replacement.
// Multisite period endpoints are not changed automatically. The last gateway
// can be removed because RGW is optional. Failed cleanup remains tracked.
func Remove(ctx context.Context, c *ceph.Container, name string) error {
	return cluster.RemoveRGW(ctx, c, name)
}

// Gateways returns the cluster's named gateway descriptors sorted by gateway
// name, including partially initialized gateways. The cluster owns their
// containers.
func Gateways(c *ceph.Container) []*Gateway {
	return cluster.Gateways(c)
}

// GatewaysContext returns sorted owned gateway descriptors, including partial
// startup attempts, while bounding the wait for fixture topology by ctx.
func GatewaysContext(ctx context.Context, c *ceph.Container) ([]*Gateway, error) {
	return cluster.GatewaysContext(ctx, c)
}

// MultisiteConfig describes a two-zone realm in fresh test clusters. The
// source is the metadata master; both zones accept object writes. ControlImage
// optionally selects a control/all CLI image for every zone. When omitted,
// each setup client uses its own cluster's control image.
type MultisiteConfig = multicluster.RGWMultisiteConfig

// Multisite owns two gateways and their CLI clients. Bridge mode adds a
// private HTTP network; host mode uses allocated gateway ports on the Docker
// host. Source and Destination expose matching ordinary S3 test credentials.
type Multisite = multicluster.RGWMultisite

// RunMultisite configures native RGW multisite on two existing clusters.
// opts customize both gateways and are applied last. Do not replace required
// networking or commands. A non-nil result returned with an error must still
// be terminated. The clusters must not already serve standalone RGW traffic.
// Both clusters must use the same network mode. Host mode advertises the
// configured daemon-host addresses, which must be mutually reachable.
// image supplies only the RGW role; setup clients use the clusters' control
// images unless ControlImage explicitly overrides them.
func RunMultisite(ctx context.Context, image string, config MultisiteConfig, opts ...testcontainers.ContainerCustomizer) (*Multisite, error) {
	return multicluster.RunRGWMultisite(ctx, image, config, opts...)
}

// SyncBucketIdentity fixes a bucket namespace and native instance. Recreating
// its name cannot silently change the bucket selected by an owned pipe.
type SyncBucketIdentity = multicluster.RGWSyncBucketIdentity

// BucketSyncStatus observes the bucket tuple captured by an owned pipe.
// Native RGW combines comparisons from matching pipes; this does not attest a
// particular pipe's activation/filter/user mode. State is sanitized: incremental,
// init, full, stopped, error, or
// disabled_or_no_sources. Native markers and error text are never returned.
type BucketSyncStatus = multicluster.RGWBucketSyncStatus

// SyncBucketSelector identifies a preexisting bucket. Its current native
// instance ID is captured and stored in the pipe, preventing a recreated name
// from silently becoming a new replication source/destination. Nil selectors
// retain Ceph's current-bucket wildcard behavior. Same-zone replication is not
// supported by native RGW multisite.
type SyncBucketSelector = multicluster.RGWSyncBucketSelector

// SyncObjectTag matches an exact key/value. Multiple pairs are ORed and
// repeated keys with different values are permitted. Native CLI comma parsing
// cannot represent comma-containing keys/values; '=' is only allowed in values.
type SyncObjectTag = multicluster.RGWSyncObjectTag

// SyncPolicyScope selects an owned zonegroup, or an existing bucket within
// that group. An empty Zonegroup selects the original source's group. Bucket
// policy fixes the native bucket instance ID and rejects a recreated name.
type SyncPolicyScope = multicluster.RGWSyncPolicyScope

// SyncGroupStatus separates permission from activation. Allowed permits a
// bucket policy to enable its subset; Enabled activates the group's pipes;
// Forbidden takes precedence over other matching enabled groups.
type SyncGroupStatus = multicluster.RGWSyncGroupStatus

type SyncGroupConfig = multicluster.RGWSyncGroupConfig

// SyncFlowConfig selects either a named symmetrical Zones set, or a
// directional SourceZone/DestinationZone pair. Directional flows have no
// native ID: leave ID and Zones empty. Zone names must be attached and owned
// by this fixture in the selected group. Bucket policies may only narrow the
// flow permitted by their parent zonegroup.
type SyncFlowConfig = multicluster.RGWSyncFlowConfig

// SyncPipeConfig selects owned zone names or a sole "*" on each side.
// Nil bucket selectors use the current bucket; an empty Prefix selects all keys.
// Source tags are ORed; when a prefix is also supplied both must match. User
// mode uses a confirmed ordinary user, or a confirmed account root with concrete
// source/destination buckets owned by that same account and no DestinationOwner.
// Principal and selected bucket tenants must match. IAM nonroot, cross-account
// and cross-tenant principal translation remain unproven and are refused.
// This helper never creates S3 buckets or grants access.
type SyncPipeConfig = multicluster.RGWSyncPipeConfig

// SyncGroup is a fresh group created by this fixture. Copies share native
// readback and lifecycle state. IDs on unrelated existing groups are never
// adopted. Native edits must not race these methods.
type SyncGroup = multicluster.RGWSyncGroup

// BucketSyncPolicyStatus describes the captured master's configuration and
// its import into one selected destination. Buckets contains copied, distinct
// native instances required by pipes selecting that destination. It contains
// no policy maps, credentials, object names or sync markers.
type BucketSyncPolicyStatus = multicluster.RGWBucketSyncPolicyStatus

// MetadataSyncStatus includes only native state/identity/shard counts. It
// omits metadata keys, markers and credentials from native diagnostic output.
type MetadataSyncStatus = multicluster.RGWMetadataSyncStatus

// DataSyncStatus summarizes the native comparison with one source's log.
// CaughtUp requires a running sync, complete incremental shards, no recovering
// shards and the native remote-log comparison. Disabled pipes do not count as
// caught up merely because an object's absence is expected.
type DataSyncStatus = multicluster.RGWDataSyncStatus

type SyncStatus = multicluster.RGWSyncStatus

// ZoneConfig assigns one fresh, independent storage cluster to a named zone.
type ZoneConfig = multicluster.RGWZoneConfig

// ZonegroupConfig defines a region and its local master zone. MasterZone
// defaults to the first zone. Object data replicates within each zonegroup;
// users and bucket metadata share the realm across zonegroups.
type ZonegroupConfig = multicluster.RGWZonegroupConfig

// TopologyConfig creates one realm spanning at least two independent zones.
// Use Zones/Zonegroup/MetadataMaster for a single region, or Zonegroups and
// MasterZonegroup for several regions with separately selected local masters.
// MetadataMaster defaults to the first zone; MasterZonegroup to the first group.
// All clusters use the same network mode and must not serve standalone RGW data.
// ControlImage optionally overrides every zone's setup client image. Otherwise
// each client uses its own cluster's control image, including added zones.
type TopologyConfig = multicluster.RGWTopologyConfig

// Zone describes one owned multisite zone. PeerEndpoint is reachable by
// gateways/CLI containers in the fixture's HTTP network or Docker host namespace.
// Applications obtain their endpoint separately with Gateway.S3Endpoint.
type Zone = multicluster.RGWZone

// Zonegroup is an owned region snapshot. MasterZone reflects the last
// topology operation; direct native promotions require a subsequent operation
// to refresh it. Each zone retains its own storage cluster and daemon endpoint.
type Zonegroup = multicluster.RGWZonegroup

// RunTopology creates a multi-zone fixture using the same ownership and
// cleanup contract as RunMultisite. The initial master becomes Source, and
// the first remaining zone becomes Destination for compatibility. Zones returns
// all sites. A non-nil result on error owns partial resources and needs cleanup.
// image selects RGW gateways; each setup client uses its cluster's control
// image unless ControlImage supplies a shared override.
func RunTopology(ctx context.Context, image string, config TopologyConfig, opts ...testcontainers.ContainerCustomizer) (*Multisite, error) {
	return multicluster.RunRGWTopology(ctx, image, config, opts...)
}
