// Code generated by internal/facadegen. DO NOT EDIT.

package ceph

import (
	"context"
	"time"

	"github.com/jsyoo5b/ceph-testcontainers-go/internal/cluster"
	"github.com/testcontainers/testcontainers-go"
)

const (
	// DefaultImage pins the multi-architecture manifest tested by this PoC.
	DefaultImage = cluster.DefaultImage
	// MessengerDefault retains Ceph's own Messenger defaults and v1/v2 MON
	// addresses. It does not imply that every connection uses encryption.
	MessengerDefault = cluster.MessengerDefault
	// MessengerV2Secure allows only encrypted Messenger v2 connections, with
	// no CRC-mode negotiation or legacy Messenger v1 listener.
	MessengerV2Secure   = cluster.MessengerV2Secure
	PublicNetworkPlane  = cluster.PublicNetworkPlane
	ClusterNetworkPlane = cluster.ClusterNetworkPlane
)

var (
	// ErrHostNetworkUnavailable reports that host mode cannot serve native clients
	// in the test process: the engine does not run Linux containers, the selected
	// address is not assigned on the Docker host, or the first MON's advertised
	// endpoint is not reachable from this process. Run returns it before creating
	// MGR/OSD daemons; later MON/RGW port reservations may also return it.
	ErrHostNetworkUnavailable = cluster.ErrHostNetworkUnavailable
)

// ClientCaps contains Cephx capability expressions, passed as individual CLI
// arguments. For example, Mon: "allow r" and OSD: "allow rw pool=data
// namespace=tenant-a" restrict RADOS I/O to one pool and namespace. Empty fields
// grant no capabilities for that service. Capabilities are never broadened by
// this helper; Ceph validates their syntax.
type ClientCaps = cluster.ClientCaps

// ClientConfig describes a client identity created by this cluster. Credentials
// remain private; ConnectionConfig returns copies for an external native client.
// The cluster owns the auth database, while callers own attached containers.
type ClientConfig = cluster.ClientConfig

// Container embeds the MON/control container and owns the MGR, OSDs, optional
// RGW/MDS services and network.
// Use Terminate to clean up the entire cluster. Generic Run options customize
// the MON; module options configure the cluster. Use WithHostNetwork to change
// cluster networking, rather than changing only the MON's network mode.
type Container = cluster.Container

// OSDContainer is one storage daemon backed by a sparse BlueStore file.
// The file is container-local unless WithOSDInMemoryStorage is selected.
// Stop/Start can be used for failure injection; RemoveOSD drains and purges it.
type OSDContainer = cluster.OSDContainer

// Run creates configurable MON, MGR and OSD containers for a disposable cluster.
// img must satisfy the control role: MON/MGR, CLI, Python clients and mirrors.
// Other roles use img unless overridden by WithOSDImage, rgw.WithImage or
// cephfs.WithMDSImage. Images contain runtime tools; this module supplies cluster setup.
// A non-nil Container returned with an error must still be terminated.
func Run(ctx context.Context, img string, opts ...testcontainers.ContainerCustomizer) (*Container, error) {
	return cluster.Run(ctx, img, opts...)
}

// WithPools creates the selected pools after initial OSD startup. Repeated
// options replace the list. Configs and nested EC settings are copied; cluster
// defaults are resolved after all Run options have been applied.
func WithPools(configs ...PoolConfig) Option {
	return cluster.WithPools(configs...)
}

// ConfigSetting addresses one entry in the MON configuration database. Section
// is global, mon, mgr, osd, mds, client or a specific identity such as osd.0.
// Mask is optional: class:ssd, host:node-a or host:node-a/class:ssd. These stored
// settings have lower precedence than local files, argv and runtime overrides.
type ConfigSetting = cluster.ConfigSetting

// ConfigEntry reports an exact stored entry rather than an inherited/default
// value. Configuration may contain sensitive values; log selected fields only.
type ConfigEntry = cluster.ConfigEntry

// ConfigOverride restores one exact database entry. Copies share lifecycle
// state. Restore explicitly when the test condition should end; cluster
// termination disposes of the entire configuration database. A non-nil handle
// returned with an error must also be restored or the cluster terminated.
type ConfigOverride = cluster.ConfigOverride

// DiagnosticsConfig bounds a read-only collection. Zero fields select a one
// minute total timeout, ten seconds per operation, 64 KiB per artifact, the last
// 1000 log lines, four workers and at most 128 containers. Additional containers
// are caller-owned clients or mirror daemons; collection never adopts them.
// RedactValues removes additional opaque application secrets. Redaction is best
// effort: arbitrary log contents still require review before sharing a report.
type DiagnosticsConfig = cluster.DiagnosticsConfig

// DiagnosticsContainer explicitly adds an external container to a report.
// Name and Role describe it; Container is only inspected and its logs read.
type DiagnosticsContainer = cluster.DiagnosticsContainer

// DiagnosticArtifact retains one observation, including incomplete output or
// an individual failure. Data is text; inspect observations are JSON when not
// truncated. Names and order are stable, but observations are not transactional.
type DiagnosticArtifact = cluster.DiagnosticArtifact

// DiagnosticsReport is an independent, JSON-serializable snapshot. Complete
// means every requested observation succeeded without byte truncation, not that
// Ceph is healthy or that replication has completed. Logs cover only LogTail.
type DiagnosticsReport = cluster.DiagnosticsReport

// BlocklistEntry reports native OSDMap fencing, including ranges created by
// external tools. Until is the MON's absolute expiration time. A listing grants
// no ownership to remove an existing entry.
type BlocklistEntry = cluster.BlocklistEntry

// BlocklistOverride owns one newly added exact client-session entry. Address
// includes a nonzero nonce, so two clients on one host remain distinct. Copies
// share restoration state. Removing the entry restores OSDMap admission; session
// recovery depends on the client library and callers may need to reconnect.
// External blocklist edits must not race helpers.
type BlocklistOverride = cluster.BlocklistOverride

// FullRatios are global OSDMap utilization thresholds, expressed as fractions
// of capacity. These are separate from central configuration and pool quotas.
// Native OSDMap storage uses float32; observations retain its normalized value.
type FullRatios = cluster.FullRatios

// FullRatioSnapshot is one native OSDMap observation. Epoch is not a generation
// for these thresholds: unrelated OSDMap changes can advance it too. The values
// describe map policy, not whether any OSD has reported the corresponding state.
type FullRatioSnapshot = cluster.FullRatioSnapshot

// FullRatiosOverride restores all three global OSDMap thresholds as one owned
// fixture. Copies share lifecycle state. The native CLI changes one threshold
// per command, so apply and restore are not atomic. A non-nil handle returned
// with an error remains tracked; restore it or terminate the disposable cluster.
type FullRatiosOverride = cluster.FullRatiosOverride

// HealthSnapshot is one MON health observation. Status reflects the worst
// unmuted check; HEALTH_OK can therefore include muted warnings or errors.
// Checks retain native, case-sensitive codes, including unknown future codes.
type HealthSnapshot = cluster.HealthSnapshot

// HealthCheck reports the native summary count and detail messages. Count is
// signed and need not equal the number of details, which Ceph may truncate.
type HealthCheck = cluster.HealthCheck

// HealthMute is a native stored mute, which can outlive its current check.
// ExpiresAt is empty for no TTL, otherwise the original Ceph timestamp:
// YYYY-MM-DDTHH:MM:SS.ffffff+HHMM (or -HHMM), or seconds.ffffff for an early
// epoch below 315360000 seconds. Expiry is not compared with the caller's clock;
// an expired or cleared nonsticky mute can remain visible before the MON tick.
type HealthMute = cluster.HealthMute

// WithIdleEntrypoint keeps a client or helper container running with
// sleep infinity under Docker's init process, so commands can be executed in it
// later. As PID 1, sleep ignores SIGTERM and Docker waits for the full stop
// timeout (10 seconds by default) before killing it; init forwards the signal
// so termination finishes at once. Init also reaps background processes that
// exit inside the container, such as a test server started through Exec.
// The entrypoint and command remain sleep and infinity.
func WithIdleEntrypoint() testcontainers.CustomizeRequestOption {
	return cluster.WithIdleEntrypoint()
}

// MessengerMode selects the fixture's immutable bootstrap connection policy.
type MessengerMode = cluster.MessengerMode

// MGRModuleState combines configured module membership with the active MGR's
// advertised module metadata. Available means metadata is present, not that
// commands are ready. CanRun is meaningful only when Available is true.
// AlwaysOn modules can be force-disabled outside this fixture; Enabled reflects
// ForceDisabled too. ErrorString is the native dependency/load diagnostic.
type MGRModuleState = cluster.MGRModuleState

// MGRModuleOverride restores one module's original enabled state. Copies share
// lifecycle state. Restore explicitly when the test condition ends; termination
// disposes of the entire cluster. A non-nil handle returned with an error must
// also be restored or the cluster terminated.
type MGRModuleOverride = cluster.MGRModuleOverride

// NetworkPlane selects the client/public or OSD replication network.
type NetworkPlane = cluster.NetworkPlane

// NetworkInterruption owns one disconnected Docker endpoint. Restore reconnects
// its original addresses and aliases without restarting the container or Ceph
// daemon. It is an endpoint-to-network interruption, not a pairwise packet filter.
// A non-nil handle returned with an error must be restored: transport failure
// cannot prove that Docker did not disconnect it. Restore is retryable.
type NetworkInterruption = cluster.NetworkInterruption

// InterruptNetwork disconnects one existing bridge endpoint. The caller owns
// the container and the returned restoration handle; this function does not
// stop a daemon, change Ceph policies or remove the network. Fixture-specific
// helpers also register restoration with their cleanup. Host networking cannot
// be interrupted through Docker endpoint operations.
func InterruptNetwork(ctx context.Context, ctr testcontainers.Container, name string) (*NetworkInterruption, error) {
	return cluster.InterruptNetwork(ctx, ctr, name)
}

// WithMessengerMode selects the Messenger policy at bootstrap. MessengerDefault
// retains Ceph's image defaults and v1/v2 addresses. MessengerV2Secure requires
// encrypted v2 connections without CRC-mode or v1 fallback, including later
// daemons and WithClient containers. This option does not enable RGW HTTP TLS.
func WithMessengerMode(mode MessengerMode) Option {
	return cluster.WithMessengerMode(mode)
}

// WithMonitorCount selects the initial monitor count. Three enables quorum
// failover tests; even counts are allowed for deliberate quorum-loss scenarios.
func WithMonitorCount(count int) Option {
	return cluster.WithMonitorCount(count)
}

// WithManagerCount starts one active manager and the remaining standbys.
func WithManagerCount(count int) Option {
	return cluster.WithManagerCount(count)
}

// WithNoInitialManagers defers the first MGR until an explicit AddManager.
// Run waits for MON quorum and requested OSDs up/in, without implying PG clean
// or MGR module readiness. Initial CephFS/RGW services and an explicit manager
// count are rejected before allocation; positive-OSD initial pools are allowed.
// The ordinary default is one MGR and WithManagerCount(0) remains invalid.
// The control image must still contain the MGR and its required dependencies.
func WithNoInitialManagers() Option {
	return cluster.WithNoInitialManagers()
}

// Option transfers cluster settings outside the monitor's container request.
type Option = cluster.Option

// WithHostNetwork places every cluster daemon and WithClient container in the
// Docker daemon's host network. MON and RGW ports are selected automatically.
// The default advertised address is 127.0.0.1 for clients on that same host.
// Run fails with ErrHostNetworkUnavailable unless the engine runs Linux
// containers and the test process reaches the first MON's advertised endpoint.
func WithHostNetwork() Option {
	return cluster.WithHostNetwork()
}

// WithSeparateClusterNetwork creates a second owned bridge for OSD replication,
// recovery and heartbeat traffic. MON/MGR/MDS/RGW and WithClient use only the
// public bridge. Docker selects both subnets. This option requires bridge mode.
func WithSeparateClusterNetwork() Option {
	return cluster.WithSeparateClusterNetwork()
}

// WithHostAddress selects a local IPv4 address to bind and advertise in host
// mode, typically the Docker host's address when Docker is remote. The address
// must be assigned on the Docker daemon host and reachable from the test
// process; Run verifies both. Requires WithHostNetwork.
func WithHostAddress(address string) Option {
	return cluster.WithHostAddress(address)
}

// WithOSDImage selects the image for initial and subsequently added OSDs.
// If omitted, OSDs use the image passed to Run. Use matching Ceph versions.
func WithOSDImage(image string) Option {
	return cluster.WithOSDImage(image)
}

// WithNoInitialOSDs starts only the selected MON/MGR topology. It keeps the
// ordinary prospective pool defaults (size 2, min_size 1) for later AddOSD calls;
// WithPoolDefaults may override them. Initial pools, CephFS/RGW services and
// explicit WithOSDCount/WithInitialOSDs options are rejected before allocation.
// No storage readiness is implied: native internal pools may have pending PGs.
// WithOSDCount(0) and WithInitialOSDs() keep their existing validation errors.
func WithNoInitialOSDs() Option {
	return cluster.WithNoInitialOSDs()
}

// WithOSDCount sets the initial number of OSD containers (default: 2).
func WithOSDCount(count int) Option {
	return cluster.WithOSDCount(count)
}

// WithInitialOSDs selects the count and logical CRUSH locations of initial OSDs.
// A subsequent WithOSDCount replaces this layout with default OSD locations.
func WithInitialOSDs(configs ...OSDConfig) Option {
	return cluster.WithInitialOSDs(configs...)
}

// WithDefaultCRUSHRoot selects placement for pools that Ceph creates itself,
// including .mgr, and for omitted PoolConfig.CRUSHRoot/OSDConfig.Root fields.
// The initial layout must contain enough OSDs in this root for the default
// replica count. Without this option the root is default.
func WithDefaultCRUSHRoot(root string) Option {
	return cluster.WithDefaultCRUSHRoot(root)
}

// WithPoolDefaults selects size/min_size for pools created by Ceph or callers.
// Without this option the fast fixture uses size=min(2, OSD count), min_size=1.
// CreatePool can override these defaults for each explicitly configured pool.
func WithPoolDefaults(replicas, minSize int) Option {
	return cluster.WithPoolDefaults(replicas, minSize)
}

// WithOSDBlockSize sets each sparse BlueStore file's logical size in bytes.
// The minimum is 64 MiB and the default remains 1 GiB. These are disposable
// files, not real disks. Small functional fixtures can use WithNoInitialOSDs
// and TemporaryConfig to skip mClock's startup capacity benchmark before
// AddOSD; the benchmark can exhaust a small file even without client data.
func WithOSDBlockSize(size int64) Option {
	return cluster.WithOSDBlockSize(size)
}

// WithOSDInMemoryStorage keeps all OSD stores in one Docker-managed tmpfs
// volume. maxBytes is a positive cluster-wide filesystem allocation ceiling,
// independent of each sparse file's logical WithOSDBlockSize. It does not
// reserve RAM or limit daemon RSS; tmpfs may swap, and a full volume fails I/O.
// An owned helper using the control image preserves data across OSD Stop/Start.
// Cluster termination discards the volume. Helper loss or Docker host/VM
// restart can lose data. Requires a Linux Docker engine with local tmpfs
// volume support, including compatible Docker Desktop engines. No host mount,
// privileged container or additional image is required. The default remains
// container-local sparse files. NoInitialOSDs defers allocation until AddOSD.
func WithOSDInMemoryStorage(maxBytes int64) Option {
	return cluster.WithOSDInMemoryStorage(maxBytes)
}

// WithStartupTimeout bounds bootstrap, readiness and topology operations.
// Each operation is also bounded by the caller's context. Default: 3 minutes.
func WithStartupTimeout(timeout time.Duration) Option {
	return cluster.WithStartupTimeout(timeout)
}

// OSDState reports authoritative OSDMap state for an owned OSD. Weight is the
// native map reweight in [0,1], not the CRUSH capacity weight. Out OSDs retain
// their containers, identities and data; absence or a replaced UUID is an error.
type OSDState = cluster.OSDState

// OSDFlagOverride restores one global OSDMap flag. Copies share lifecycle state.
// Restore explicitly when the condition should end; termination disposes of
// the entire OSDMap. A non-nil handle returned with an error remains tracked and
// must be restored or the cluster terminated. Unrelated flags are never changed.
type OSDFlagOverride = cluster.OSDFlagOverride

// ContainerPause owns one container frozen through Docker's cgroup freezer.
// Resume thaws it without restarting the process. A non-nil handle returned
// with an error must be resumed: a transport failure cannot prove that Docker
// did not freeze the container. Resume is retryable and idempotent.
type ContainerPause = cluster.ContainerPause

// OSDConfig places a container's OSD in the logical CRUSH hierarchy.
// Root defaults to the cluster's selected default root, Host defaults to osd-ID, and Rack/DeviceClass
// are optional. Multiple OSDs may share a host or rack for domain-failure tests.
type OSDConfig = cluster.OSDConfig

// PoolConfig describes a pool in the disposable, file-backed cluster.
// Zero PGNum selects 8 PGs with autoscaling disabled. A nil ErasureCode creates
// a replicated pool, with the cluster's replica/min-size defaults when omitted
// (normally 2/1, or 1/1 for one initial OSD). Application
// can be rados, rbd, cephfs, rgw or a custom name; empty leaves it unassigned.
type PoolConfig = cluster.PoolConfig

// ErasureCodeConfig selects data (K) and parity (M) shards on separate failure
// domains using PoolConfig's placement fields. The fixture uses the portable
// Jerasure reed_sol_van plugin. Replicas must be zero; zero MinSize selects K+1. An explicit
// MinSize of K permits I/O without any spare shard during a failure.
// AllowOverwrites enables partial object writes and is required for RBD and
// CephFS data pools. Their metadata must remain in a replicated pool.
type ErasureCodeConfig = cluster.ErasureCodeConfig

// Pool identifies the pool, CRUSH rule and optional EC profile created for a
// fixture. PoolConfig contains the resolved defaults. Cluster termination
// disposes of its data together with the rest of the cluster.
type Pool = cluster.Pool

// PoolPGSnapshot contains one pool's reported PGs, bracketed by two native
// OSDMap observations. PoolBefore and PoolAfter reuse PoolState policy fields;
// their names and IDs agree, but policies and OSDMap epochs may differ.
// These reads are not an atomic placement snapshot. PGReady is the native MGR
// flag: false can accompany reports, and true can still accompany unknown PGs.
type PoolPGSnapshot = cluster.PoolPGSnapshot

// PGState retains native reported placement and statistics. Up and Acting
// preserve order, empty vectors and repeated missing EC shard slots
// (CRUSH_ITEM_NONE, 2147483647). Primaries are explicit reported values, not
// inferred from the vectors; -1 means no primary. Epochs can be zero or older
// than the OSDMap brackets, and State retains unknown or future native states.
// A reported OSD may have been removed or be outside fixture ownership.
type PGState = cluster.PGState

// PGStats contains signed native PG counters. Bytes counts logical payload,
// not physical disk allocation; ObjectCopies is separate from logical Objects.
// Reports arrive asynchronously, including when StatsInvalid is false, so
// these counters are not an I/O visibility or redistribution barrier.
type PGStats = cluster.PGStats

// PoolQuota limits logical bytes and object count. Zero removes that limit.
// Enforcement depends on asynchronously reported PG statistics, so the quota
// is not a strict per-write accounting boundary.
type PoolQuota = cluster.PoolQuota

// PoolState is an authoritative snapshot of a native pool, including pools
// created by services or through Ceph. Size is replica count or EC shard count.
// It does not change when a policy is subsequently updated. PGNum is the
// current count; the target and pending fields show a split or merge still in
// progress and are zero when the native map omits them.
type PoolState = cluster.PoolState

// PoolPlacement selects the CRUSH hierarchy of a replicated pool after creation.
// Its fields have PoolConfig's meaning and defaults: empty FailureDomain uses
// osd, empty CRUSHRoot uses default and empty DeviceClass leaves class unset.
type PoolPlacement = cluster.PoolPlacement

// PoolUsageSnapshot is one monitor-reported pool usage observation. StoredBytes
// estimates logical user data (DATA + OMAP); AllocatedBytes includes replication
// or EC and allocation overhead, but not the BlueStore database. All sizes are
// bytes, Objects is a logical count, and UsedRatio is a fraction in [0, 1].
// MaxAvailableBytes estimates writable logical capacity. PG reports arrive
// asynchronously: this is neither a read-after-write barrier nor a quota check.
type PoolUsageSnapshot = cluster.PoolUsageSnapshot

// InconsistentObject is one object reported by the last deep scrub of a PG.
// Errors are object-level native error names and UnionShardErrors combine the
// per-shard names, such as read_error or data_digest_mismatch.
type InconsistentObject = cluster.InconsistentObject

// InconsistentShard retains one native shard report. Shard is -1 for
// replicated pools.
type InconsistentShard = cluster.InconsistentShard

// Status contains the subset of ceph status JSON used for readiness.
// Use Ceph for other commands or the full JSON response.
type Status = cluster.Status

// MonitorContainer is an owned quorum member. Stop/Start preserves its store;
// RemoveMonitor explicitly removes membership and deletes the container.
type MonitorContainer = cluster.MonitorContainer

// ManagerContainer is an owned active or standby manager.
type ManagerContainer = cluster.ManagerContainer

// QuorumStatus contains the actual quorum and advertised monitor addresses.
type QuorumStatus = cluster.QuorumStatus

// ManagerStatus reports active ownership and registered standbys.
type ManagerStatus = cluster.ManagerStatus
